[project]
name = "ECO2Auto"
version = "0.2.0"
description = "ECO2 Automate"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cx-freeze>=8.3.0",
    "cyclopts>=3.22.3",
    "fastexcel>=0.14.0",
    "loguru>=0.7.3",
    "more-itertools>=10.7.0",
    "polars>=1.31.0",
    "pywinauto>=0.6.9",
    "rich>=14.0.0",
    "tqdm>=4.67.1",
    "whenever>=0.8.8",
    "xlsxwriter>=3.2.5",
]

[dependency-groups]
dev = ["mypy>=1.17.0", "ruff>=0.12.4"]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."

[tool.ruff]
preview = true
output-format = "concise"
extend-exclude = ["build"]

[tool.ruff.format]
preview = true
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN",  # flake8-annotations
    "COM",  # flake8-commas
    "CPY",  # flake8-copyright
    "D1",   # pydocstyle: D1*
    "FIX",  # flake8-fixme
    "Q",    # flake8-quotes
    "S101", # flake8-bandit: assert
    "TD",   # flake8-todos
]
extend-safe-fixes = [
    "EM", # flake8-errmsg
    "TC", # flake8-type-checking
]
future-annotations = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
disable_error_code = ["import-untyped", "import", "var-annotated"]
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true

[tool.cxfreeze]
executables = [{ script = "eco2auto/app.py" }]

[tool.cxfreeze.build_exe]
build_exe = "build/ECO2Auto"
includes = ["pywinauto", "comtypes.stream", "polars", "fastexcel"]
